baseURL = "https://energyflash.powertrader.es/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    # Solo dejamos una descripción
    description = "Inteligencia diaria de mercados y análisis de precios de energía"
    author = "PowerTrader"
    disableThemeToggle = false
    defaultTheme = "dark"
    ShowPostNavLinks = true
    subname = "EnergyFlash"
    homeText = "Bienvenido a EnergyFlash. Aquí encontrarás el análisis diario del pool eléctrico, precios OMIE y tendencias del mercado mayorista."

    [params.assets]
        disableHLJS = true 

    [params.social]
        linkedin = "https://linkedin.com/in/tu-usuario"
        x = "https://x.com/tu-usuario"

# --- BLOQUE DE SEGURIDAD PARA VER LAS TABLAS HTML ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menú de navegación
[[menu.main]]
    identifier = "universe"
    name = "⮌ Volver a PowerTrader"
    url = "https://powertrader.es"
    weight = 10

[sitemap]
  changefreq = "daily"
  priority = 0.8
  filename = "sitemap.xml"
