baseURL = "https://energyflash.netlify.app/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    description = "Inteligencia diaria de mercados"
    author = "PowerTrader"

    [params.assets]
        disableHLJS = true # Excelente para mantener la web ligera

# --- BLOQUE DE SEGURIDAD PARA VER LAS TABLAS HTML ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
