baseURL = "https://energyflash.powertrader.es/"
languageCode = "es-es"
title = "PowerTrader EnergyFlash"
theme = "PaperMod"

[params]
    env = "production"
    title = "PowerTrader EnergyFlash"
    description = "Inteligencia diaria de mercados"
    author = "PowerTrader"

    [params.assets]
        disableHLJS = true # Excelente para mantener la web ligera

# --- BLOQUE DE SEGURIDAD PARA VER LAS TABLAS HTML ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Añadir al final del archivo hugo.toml
[[menu.main]]
    identifier = "universe"
    name = "⮌ Volver a PowerTrader"
    url = "https://www.powertrader.es"
    weight = 10

[sitemap]
  changefreq = "daily"
  priority = 0.8
  filename = "sitemap.xml"
